apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: auth-app
spec:
  template:
    metadata:
      name: my-pod-rc
      labels:
        app: auth-app
    spec:
      containers:
        - name: my-cont-rc
          image: httpd
          ports:
            - containerPort: 80
  replicas: 4
  selector:
    app: auth-app
